# generated by datamodel-codegen:
#   filename:  workdir/s3_aws_upbound_io_v1beta1_bucketnotification.yaml

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class DeletionPolicy(Enum):
    Orphan = 'Orphan'
    Delete = 'Delete'


class Resolution(Enum):
    Required = 'Required'
    Optional = 'Optional'


class Resolve(Enum):
    Always = 'Always'
    IfNotPresent = 'IfNotPresent'


class Policy(BaseModel):
    resolution: Optional[Resolution] = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Optional[Resolve] = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class BucketRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class BucketSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class LambdaFunctionItem(BaseModel):
    events: Optional[List[str]] = None
    """
    Event for which to send notifications.
    """
    filterPrefix: Optional[str] = None
    """
    Object key name prefix.
    """
    filterSuffix: Optional[str] = None
    """
    Object key name suffix.
    """
    id: Optional[str] = None
    """
    Unique identifier for each of the notification configurations.
    """
    lambdaFunctionArn: Optional[str] = None
    """
    Lambda function ARN.
    """


class QueueArnRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class QueueArnSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class QueueItem(BaseModel):
    events: Optional[List[str]] = None
    """
    Specifies event for which to send notifications.
    """
    filterPrefix: Optional[str] = None
    """
    Object key name prefix.
    """
    filterSuffix: Optional[str] = None
    """
    Object key name suffix.
    """
    id: Optional[str] = None
    """
    Unique identifier for each of the notification configurations.
    """
    queueArn: Optional[str] = None
    """
    SQS queue ARN.
    """
    queueArnRef: Optional[QueueArnRef] = None
    """
    Reference to a Queue in sqs to populate queueArn.
    """
    queueArnSelector: Optional[QueueArnSelector] = None
    """
    Selector for a Queue in sqs to populate queueArn.
    """


class TopicArnRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class TopicArnSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class TopicItem(BaseModel):
    events: Optional[List[str]] = None
    """
    Event for which to send notifications.
    """
    filterPrefix: Optional[str] = None
    """
    Object key name prefix.
    """
    filterSuffix: Optional[str] = None
    """
    Object key name suffix.
    """
    id: Optional[str] = None
    """
    Unique identifier for each of the notification configurations.
    """
    topicArn: Optional[str] = None
    """
    SNS topic ARN.
    """
    topicArnRef: Optional[TopicArnRef] = None
    """
    Reference to a Topic in sns to populate topicArn.
    """
    topicArnSelector: Optional[TopicArnSelector] = None
    """
    Selector for a Topic in sns to populate topicArn.
    """


class ForProvider(BaseModel):
    bucket: Optional[str] = None
    """
    Name of the bucket for notification configuration.
    """
    bucketRef: Optional[BucketRef] = None
    """
    Reference to a Bucket in s3 to populate bucket.
    """
    bucketSelector: Optional[BucketSelector] = None
    """
    Selector for a Bucket in s3 to populate bucket.
    """
    eventbridge: Optional[bool] = None
    """
    Whether to enable Amazon EventBridge notifications. Defaults to false.
    """
    lambdaFunction: Optional[List[LambdaFunctionItem]] = None
    """
    Used to configure notifications to a Lambda Function. See below.
    """
    queue: Optional[List[QueueItem]] = None
    """
    Notification configuration to SQS Queue. See below.
    """
    region: str
    """
    Region is the region you'd like your resource to be created in.
    """
    topic: Optional[List[TopicItem]] = None
    """
    Notification configuration to SNS Topic. See below.
    """


class InitProvider(BaseModel):
    bucket: Optional[str] = None
    """
    Name of the bucket for notification configuration.
    """
    bucketRef: Optional[BucketRef] = None
    """
    Reference to a Bucket in s3 to populate bucket.
    """
    bucketSelector: Optional[BucketSelector] = None
    """
    Selector for a Bucket in s3 to populate bucket.
    """
    eventbridge: Optional[bool] = None
    """
    Whether to enable Amazon EventBridge notifications. Defaults to false.
    """
    lambdaFunction: Optional[List[LambdaFunctionItem]] = None
    """
    Used to configure notifications to a Lambda Function. See below.
    """
    queue: Optional[List[QueueItem]] = None
    """
    Notification configuration to SQS Queue. See below.
    """
    topic: Optional[List[TopicItem]] = None
    """
    Notification configuration to SNS Topic. See below.
    """


class ManagementPolicy(Enum):
    Observe = 'Observe'
    Create = 'Create'
    Update = 'Update'
    Delete = 'Delete'
    LateInitialize = 'LateInitialize'
    field_ = '*'


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class ConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class Metadata(BaseModel):
    annotations: Optional[Dict[str, str]] = None
    """
    Annotations are the annotations to be added to connection secret.
    - For Kubernetes secrets, this will be used as "metadata.annotations".
    - It is up to Secret Store implementation for others store types.
    """
    labels: Optional[Dict[str, str]] = None
    """
    Labels are the labels/tags to be added to connection secret.
    - For Kubernetes secrets, this will be used as "metadata.labels".
    - It is up to Secret Store implementation for others store types.
    """
    type: Optional[str] = None
    """
    Type is the SecretType for the connection secret.
    - Only valid for Kubernetes Secret Stores.
    """


class PublishConnectionDetailsTo(BaseModel):
    configRef: Optional[ConfigRef] = Field(
        default_factory=lambda: ConfigRef.model_validate({'name': 'default'})
    )
    """
    SecretStoreConfigRef specifies which secret store config should be used
    for this ConnectionSecret.
    """
    metadata: Optional[Metadata] = None
    """
    Metadata is the metadata for connection secret.
    """
    name: str
    """
    Name is the name of the connection secret.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Optional[DeletionPolicy] = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: Optional[InitProvider] = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: Optional[List[ManagementPolicy]] = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: Optional[ProviderConfigRef] = Field(
        default_factory=lambda: ProviderConfigRef.model_validate({'name': 'default'})
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    publishConnectionDetailsTo: Optional[PublishConnectionDetailsTo] = None
    """
    PublishConnectionDetailsTo specifies the connection secret config which
    contains a name, metadata and a reference to secret store config to
    which any connection details for this managed resource should be written.
    Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    This field is planned to be replaced in a future release in favor of
    PublishConnectionDetailsTo. Currently, both could be set independently
    and connection details would be published to both without affecting
    each other.
    """


class QueueItemModel(BaseModel):
    events: Optional[List[str]] = None
    """
    Specifies event for which to send notifications.
    """
    filterPrefix: Optional[str] = None
    """
    Object key name prefix.
    """
    filterSuffix: Optional[str] = None
    """
    Object key name suffix.
    """
    id: Optional[str] = None
    """
    Unique identifier for each of the notification configurations.
    """
    queueArn: Optional[str] = None
    """
    SQS queue ARN.
    """


class TopicItemModel(BaseModel):
    events: Optional[List[str]] = None
    """
    Event for which to send notifications.
    """
    filterPrefix: Optional[str] = None
    """
    Object key name prefix.
    """
    filterSuffix: Optional[str] = None
    """
    Object key name suffix.
    """
    id: Optional[str] = None
    """
    Unique identifier for each of the notification configurations.
    """
    topicArn: Optional[str] = None
    """
    SNS topic ARN.
    """


class AtProvider(BaseModel):
    bucket: Optional[str] = None
    """
    Name of the bucket for notification configuration.
    """
    eventbridge: Optional[bool] = None
    """
    Whether to enable Amazon EventBridge notifications. Defaults to false.
    """
    id: Optional[str] = None
    """
    Unique identifier for each of the notification configurations.
    """
    lambdaFunction: Optional[List[LambdaFunctionItem]] = None
    """
    Used to configure notifications to a Lambda Function. See below.
    """
    queue: Optional[List[QueueItemModel]] = None
    """
    Notification configuration to SQS Queue. See below.
    """
    topic: Optional[List[TopicItemModel]] = None
    """
    Notification configuration to SNS Topic. See below.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: Optional[AtProvider] = None
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class BucketNotification(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    BucketNotificationSpec defines the desired state of BucketNotification
    """
    status: Optional[Status] = None
    """
    BucketNotificationStatus defines the observed state of BucketNotification.
    """


class BucketNotificationList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[BucketNotification]
    """
    List of bucketnotifications. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """